---

- name: Create Temporary Storage Folder
  file:
    path: "{{ java_tmp_storage }}"
    state: directory
  when: java_type == "Oracle"

- name: Download Oracle Java RPM
  get_url:
    url: "{{ __java_oracle_download }}"
    headers: 'Cookie:oraclelicense=accept-secure-backup-cookie'
    dest: "{{ java_tmp_storage }}/{{ __java_oracle_rpm }}.rpm"
    checksum: "{{ __java_oracle_download_checksum }}"
  when: java_type == "Oracle"

- name: Install Oracle Java
  package:
    name: "{{ java_tmp_storage }}/{{ __java_oracle_rpm }}.rpm"
    state: installed
  when: java_type == "Oracle"

- name: Install Open Java
  yum:
    name: "{{ __java_open_package }}"
    state: installed
  when: java_type == "Open"

- name: Check For Installed jvm
  command: /usr/bin/ls /usr/lib/jvm
  register: __java_redhat_open
  changed_when: False
  ignore_errors: True
  when: java_type == "Open"

- debug: var=__java_redhat_open
  when: java_type == "Open"
